### ISSUE TITLE
Deep-links/Permalinks to imagery items on original platform

### ISSUE THREAD

**Issue by jo-chemla** [Iconem/search-satellite-imagery#11]
Helps order making/deep-links when available (no deep-links for any platform when checked unfortunately): make selection, export requests email with scene IDs, permalinks. 
 
```[tasklist]
### Tasks
- [ ] EOS has clean permalinks
- [ ] Skyfi has clean permalinks (but no cors so search fails)
- [ ] Maxar sends post request to https://api.discover.digitalglobe.com/v1/store
- [ ] Skywatch and Up42 don't have them yet, but hopefully being implemented (twitter)
- [ ] head-aerospace post request to generate permalink is not very clean. 
```
