### ISSUE TITLE
Integrate constellations directly - without aggregators middlemen

### ISSUE THREAD

**Issue by jo-chemla** [Iconem/search-satellite-imagery#2]
To discuss since no flow for ordering atm: Integrate already aggregated constellations directly if authorized to do so, (would then indicate unknown price since often under NDA)
```[tasklist]
### Tasks
- [ ] [Planet](https://developers.planet.com/docs/apis/data/reference/#tag/Item-Search/operation/ListSearches)
- [ ]  [Airbus OneAtlas Pleiades directly](https://api.oneatlas.airbus.com/guides/oneatlas-data/g-search/)
- [ ] [Vexcel API](https://vexcel.atlassian.net/wiki/spaces/APIDOCS/pages/2131886750/FindImagesInPolygon+Service+-+v1.4)
```
